//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visning
    {
        public int id { get; set; }
        public string movieid { get; set; }
        public string salong { get; set; }
        public int maxseats { get; set; }
        public System.DateTime date { get; set; }
    }
}
